### ISSUE TITLE
Hi! I am waiting for your response and kind reply .

### ISSUE THREAD

**Issue by unizard** [etrulls/deepdesc-release#1]
Hi! My name is yukyung choi.
I read your deep-descriptors and waiting for your providing code.
When I could download this one?
Thank you in advance.

Best regard,
Yukyung choi

**Comment by bobbens** [comment]
Hello, we hit a few snags with incompatibilities with old torch files, but will try to make it available as soon as possible.

**Comment by bobbens** [comment]
It's available.
