### ISSUE TITLE
error "/home/username/torch/install/lib/lua/5.1/libTHCUNN.so: undefined symbol: THCudaBlas_gemm"

### ISSUE THREAD

**Issue by fybaft2012** [etrulls/deepdesc-release#4]
Hello all,
When I run the 'example.lua', it gave the erroe:
'symbol lookup error: /home/username/torch/install/lib/lua/5.1/libTHCUNN.so: undefined symbol: THCudaBlas_gemm'
So can you give me some advice how to fix it?
Thank you very much !

**Comment by rrmenon10** [comment]
How did you solve it?
